version: 2.1
workflows:
  run:
    jobs:
      - plan:
          filters:
            branches:
              only: master
          context: Nomad Run
  plan:
    jobs:
      - plan:
          filters:
            branches:
              ignore: master
          context: Nomad Plan

jobs:
  plan:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: yarn global add @srnd/vagabond
      - run: cd jobs && $(yarn global bin)/vagabond plan-all
