#cloud-config
puppet:
  install: true

package_upgrade: true
packages:
  - git
  - curl
  - jq

write_files:
  - path: /etc/nomad.env
    owner: root
    permissions: 0660
    content: |
      host=azure
      speed=gbps
  - path: /opt/apply_puppet.sh
    owner: root
    permissions: 0775
    content: |
      #!/usr/bin/env bash
      if [ ! -e "/opt/config" ]; then
        git clone https://github.com/codeday/containercfg.git /opt/config
      fi

      cd /opt/config
      git pull origin master

      cd /opt/config/agents/puppet
      export FACTERLIB=/opt/config/agents/puppet/facts/

      r10k puppetfile install --verbose
      puppet apply . --modulepath /etc/puppet/modules:/opt/config/agents/puppet/modules

runcmd:
  - curl -sL https://aka.ms/InstallAzureCLIDeb | bash
  - sudo gem install r10k
  - puppet resource cron puppet-apply ensure=present user=root minute='*/15' command='/opt/apply_puppet.sh'
  - /opt/apply_puppet.sh
