#cloud-config
puppet:
  install: true

package_upgrade: true
packages:
  - git
  - curl
  - jq

write_files:
  - path: /opt/apply_puppet.sh
    owner: root
    permissions: 0775
    content: |
      #!/usr/bin/env bash
      if [ -e "/opt/config" ]; then
        git checkout https://github.com/srnd/NomadJobs.git /opt/config
      fi

      cd /opt/config
      git pull origin master

      MDS="http://169.254.169.254/metadata/instance/compute?api-version=2019-08-15"
      export FACTER_role=$(curl -H Metadata:true "$MDS" 2>/dev/null | jq -r '.tagsList[] | select(.name == "role").value')

      cd /opt/config/agents/puppet

      r10k puppetfile install
      puppet apply . --logdest syslog --modulepath /etc/puppet/modules:/opt/config/agents/puppet/modules

runcmd:
  - sudo gem install r10k
  - puppet resource cron puppet-apply ensure=present user=root minute=30 command='/opt/apply_puppet.sh'
  - /opt/apply_puppet.sh
